targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          build_extensions:
            '^lib/app/model/concrete/{{}}.dart': 'lib/app/model/concrete/model_g/{{}}.g.dart'